version: '3'
services:
  app:
    build: .
    image: nfc-bus-payment-system:latest
    ports:
      - "3000:3000"

    volumes:
      - .:/usr/src/app
      - .:/usr/src/node_modules
    env_file:
      - .env